---
title: MACROMANAGERS
description: The Macroeconomics of Managers
url: 
baseurl: 
lang: en
permalink: "/:title/"

plausible: macromanagers.eu

paginate: 4
paginate_path: "/blog/:num/" 

markdown: kramdown
highlighter: rouge

plugins:
- jekyll-seo-tag
- jekyll-paginate

exclude:
- vendor
- ".bundle"
- ".sass-cache"
- config
- Gemfile
- Gemfile.lock
- node_modules
- log
- tmp
- Rakefile
- package.json
- CHANGELOG
- LICENSE
- README
- "/docs"

livereload: true

collections:
  publications:
    output: true
    permalink: /:collection/:name
  courses:
    output: true
    permalink: /:collection/:name
  posts:
    output: true
    permalink: /:collection/:name
  software:
    output: false
  events:
    output: true
    permalink: /:collection/:name
  datasets:
    output: true
    permalink: /:collection/:name

# Defaults
defaults:
  - scope:
      path: ""
      type: publications
    values:
      layout: publication
  - scope:
      path: ""
      type: courses
    values:
      layout: course
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: events
    values:
      layout: event
  - scope:
      path: ""
      type: datasets
    values:
      layout: dataset
navbar:
  publications:
  - text: Publications
    url: "/"
  - text: CV
    url: "/cv/"
  - text: Project
    url: "/project/"
  - text: More
    dropdown:
    - text: Courses
      url: "https://koren.dev"
    - text: Software
      url: "https://koren.dev/software/"
    - text: Blog
      url: "https://codedthinking.com"
    - text: Codedthinking Story
      url: "https://codedthinking.com/story/"

  courses:
  - text: Courses
    url: "/"
  - text: Software
    url: "/software/"
  - text: More
    dropdown:
    - text: Publications
      url: "https://koren.mk"
    - text: CV
      url: "https://koren.mk/cv/"
    - text: Blog
      url: "https://codedthinking.com"
    - text: Codedthinking Story
      url: "https://codedthinking.com/story/"

  blog:
  - text: Blog
    url: "/"
  - text: The story
    url: "/story/"
  - text: More
    dropdown:
    - text: Courses
      url: "https://koren.dev"
    - text: Software
      url: "https://koren.dev/software/"
    - text: Publications
      url: "https://koren.mk"
    - text: CV
      url: "https://koren.mk/cv/"
config:
  social:
    facebook: "#"
    twitter: "#"
    instagram: "#"
    linkedin: "#"
    google: "#"
    github: "#"

  publications:
    logo: /assets/images/koren-mk.svg
    copyright: "&copy; 2023 Koren.mk"
    url: https://koren.mk

  courses:
    logo: /assets/images/koren-dev.svg
    copyright: "&copy; 2023 Koren.dev"
    url: https://koren.dev

  blog:
    logo: /assets/images/koren-ct.svg
    copyright: "&copy; 2023 Coded Thinking OÜ"
    url: https://codedthinking.com
