---
title: MACROMANAGERS
description: The Macroeconomics of Managers
baseurl: 
lang: en
permalink: "/:title/"

plausible: macromanagers.eu

paginate: 4
paginate_path: "/blog/:num/" 

markdown: kramdown
highlighter: rouge

plugins:
- jekyll-seo-tag
- jekyll-paginate

exclude:
- vendor
- ".bundle"
- ".sass-cache"
- config
- Gemfile
- Gemfile.lock
- node_modules
- log
- tmp
- Rakefile
- package.json
- CHANGELOG
- LICENSE
- README
- "/docs"

livereload: true

collections:
  publications:
    output: true
    permalink: /:collection/:name
  courses:
    output: true
    permalink: /:collection/:name
  posts:
    output: true
    permalink: /:collection/:name
  software:
    output: false
  events:
    output: true
    permalink: /:collection/:name
  datasets:
    output: true
    permalink: /:collection/:name

# Defaults
defaults:
  - scope:
      path: ""
      type: publications
    values:
      layout: publication
  - scope:
      path: ""
      type: courses
    values:
      layout: course
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: events
    values:
      layout: event
  - scope:
      path: ""
      type: datasets
    values:
      layout: dataset
social:
  twitter: "https://twitter.com/korenmiklos"
  google: "https://scholar.google.com/citations?user=fFTegXUAAAAJ"
  github: "https://github.com/korenmiklos"
logo: /assets/images/logo.svg
logo_light: /assets/images/logo-light.svg
copyright: "&copy; 2024 HUN-REN KRTK"
url: https://macromanagers.eu
navbar:
  - text: Project
    url: "/project/"
  - text: Events
    url: "/events/"
  - text: Datasets
    url: "/datasets/"
  - text: More
    dropdown:
    - text: Publications
      url: "/publications/"
    - text: Media mentions
      url: "/mentions/"
