social:
  twitter: "https://twitter.com/korenmiklos"
  google: "https://scholar.google.com/citations?user=fFTegXUAAAAJ"
  github: "https://github.com/korenmiklos"

logo: /assets/images/logo.svg
logo_light: /assets/images/logo-light.svg
copyright: "&copy; 2023 HUN-REN KRTK"
url: https://macromanagers.eu
