social:
  facebook: "#"
  twitter: "#"
  instagram: "#"
  linkedin: "#"
  google: "#"
  github: "#"

logo: /assets/images/logo.svg
logo_light: /assets/images/logo-light.svg
copyright: "&copy; 2023 Coded Thinking OÜ"
url: https://codedthinking.com
